// Cenário FIAP NEXT 2026 — planta ILUSTRATIVA (layout fictício; nomes de empresas só como rótulo de stand).
// node db/seed/next.mjs [--sql]
import { cenario } from './lib.mjs';

cenario({
  arquivo: 'next.mjs', sql: '14_seed_next.sql',
  evento: { codigo: 'NEXT26', nome: 'FIAP NEXT 2026', local: 'Pavilhão principal', largura_px: 1400, altura_px: 1000, escala_m_px: 0.2,
            descricao: 'Planta ilustrativa para demonstração — layout fictício.', origem_padrao: 'ENT' },
  // codigo, nome, tipo, x, y, w, h, cor, subtitulo
  areas: [
    ['A_AWS', 'AWS', 'STAND', 180, 180, 140, 130, '#ff9900', 'Cloud Street', 'Stand com demonstrações de serviços de nuvem.'],
    ['A_AZURE', 'Microsoft Azure', 'STAND', 330, 180, 140, 130, '#2f8fe8', 'Cloud Street', 'Stand com demonstrações de serviços de nuvem e IA.'],
    ['A_GCP', 'Google Cloud', 'STAND', 180, 340, 140, 130, '#34a853', 'Cloud Street', 'Stand com demonstrações de nuvem e dados.'],
    ['A_IBM', 'IBM', 'STAND', 330, 340, 140, 130, '#6f8cff', 'Cloud Street', 'Stand com demonstrações de IA para empresas.'],
    ['A_ARENA', 'Arena Tech4Change', 'ARENA', 530, 180, 290, 290, '#a855f7', 'Final do hackathon', 'Onde acontece a final do hackathon Tech4Change. Fica barulhenta durante as apresentações.'],
    ['A_PALCO', 'Palco Principal', 'PALCO', 880, 180, 290, 290, '#ef4444', 'Keynotes', 'Keynotes e shows. É a área mais barulhenta do evento.'],
    ['A_TEC', 'Streaming', 'TECNICA', 1230, 180, 110, 290, '#475569', 'Área técnica', 'Área técnica de transmissão. Acesso restrito à equipe.'],
    ['A_ALIM', 'Praça de Alimentação', 'ALIMENTACAO', 180, 530, 290, 140, '#f59e0b', null, 'Food trucks e mesas. Costuma lotar no horário do almoço, das 12h às 14h.'],
    ['A_STARTUPS', 'Startups FIAP', 'STAND', 180, 690, 290, 130, '#22d3ee', 'Vila de startups', 'Vila com estandes de startups de alunos e ex-alunos.'],
    ['A_NVIDIA', 'NVIDIA', 'STAND', 530, 530, 140, 290, '#76b900', 'IA & GPUs', 'Stand com demonstrações de IA e computação acelerada.'],
    ['A_LABS', 'FIAP Labs', 'STAND', 680, 530, 140, 290, '#ed145b', 'Robótica & IA', 'Robótica, IoT e projetos de alunos, com demonstrações práticas.'],
    ['A_ORACLE', 'Oracle Cloud', 'STAND', 880, 530, 290, 100, '#c74634', 'OCI · Autonomous AI Database', 'Stand com demonstrações de OCI e Autonomous AI Database.'],
    ['A_CORR', 'Corredor Interno', 'CORREDOR', 1045, 630, 30, 220, null, null, 'Passagem estreita entre o stand da Oracle e a Rua Sul. Costuma lotar.'],
    ['A_WC', 'Banheiro Adaptado', 'BANHEIRO_ADAP', 880, 670, 150, 150, '#38bdf8', null, 'Banheiro adaptado com barras de apoio e espaço para cadeira de rodas.'],
    ['A_ACOLH', 'Sala de Acolhimento', 'ACOLHIMENTO', 1085, 670, 85, 150, '#2dd4bf', 'Espaço sensorial', 'Espaço silencioso com luz baixa, abafadores de ruído e equipe treinada. Aberto o dia todo.'],
    ['A_RAMPA', 'Rampa Leste', 'RAMPA', 1275, 530, 50, 290, '#84cc16', null, 'Rampa acessível entre o Boulevard e a Rua Sul, alternativa aos degraus de serviço.'],
    ['A_CRED', 'Credenciamento', 'SERVICO', 20, 560, 110, 70, '#64748b', null, 'Retirada de crachás e das pulseiras de atendimento prioritário.'],
    ['A_BRIG', 'Brigada / Enfermaria', 'SERVICO', 1180, 880, 140, 60, '#f43f5e', null, 'Primeiros socorros e brigada de incêndio.'],
  ],
  pontos: [
    ['ENT', 'Entrada / Saída Principal', 'SAIDA', 50, 500],
    ['SN', 'Saída de Emergência Norte', 'SAIDA', 500, 50],
    ['SL', 'Saída de Emergência Leste (degraus)', 'SAIDA', 1350, 150],
    ['SS', 'Saída de Emergência Sul', 'SAIDA', 850, 950],
    ['SO', 'Saída de Emergência Oeste', 'SAIDA', 50, 850],
    ['J11', 'Rua Norte × Av. Oeste', 'CRUZAMENTO', 150, 150],
    ['J21', 'Rua Norte × Av. A', 'CRUZAMENTO', 500, 150],
    ['J31', 'Rua Norte × Av. B', 'CRUZAMENTO', 850, 150],
    ['J41', 'Rua Norte × Av. Leste', 'CRUZAMENTO', 1200, 150],
    ['J12', 'Boulevard × Av. Oeste', 'CRUZAMENTO', 150, 500],
    ['J22', 'Boulevard × Av. A', 'CRUZAMENTO', 500, 500],
    ['J32', 'Boulevard × Av. B', 'CRUZAMENTO', 850, 500],
    ['J42', 'Boulevard × Av. Leste', 'CRUZAMENTO', 1200, 500],
    ['J13', 'Rua Sul × Av. Oeste', 'CRUZAMENTO', 150, 850],
    ['J23', 'Rua Sul × Av. A', 'CRUZAMENTO', 500, 850],
    ['J33', 'Rua Sul × Av. B', 'CRUZAMENTO', 850, 850],
    ['J43', 'Rua Sul × Av. Leste', 'CRUZAMENTO', 1200, 850],
    ['R1', 'Rampa Leste (topo)', 'RAMPA', 1300, 500],
    ['R2', 'Rampa Leste (base)', 'RAMPA', 1300, 850],
    ['CI', 'Corredor Interno × Rua Sul', 'CRUZAMENTO', 1060, 850],
    ['AWS', 'Stand AWS', 'STAND', 250, 150],
    ['AZURE', 'Stand Microsoft Azure', 'STAND', 400, 150],
    ['GCP', 'Stand Google Cloud', 'STAND', 250, 500],
    ['IBM', 'Stand IBM', 'STAND', 400, 500],
    ['ARENA', 'Arena Tech4Change', 'ARENA', 675, 500],
    ['PALCO', 'Palco Principal', 'PALCO', 960, 500],
    ['ORACLE', 'Stand Oracle Cloud', 'STAND', 1060, 500],
    ['CRED', 'Credenciamento', 'SERVICO', 150, 560],
    ['ALIM', 'Praça de Alimentação', 'ALIMENTACAO', 150, 600],
    ['STARTUPS', 'Startups FIAP', 'STAND', 150, 755],
    ['NVIDIA', 'Stand NVIDIA', 'STAND', 600, 850],
    ['LABS', 'FIAP Labs', 'STAND', 750, 850],
    ['WC', 'Banheiro Adaptado', 'BANHEIRO_ADAP', 850, 700],
    ['ACOLH', 'Sala de Acolhimento', 'ACOLHIMENTO', 1130, 850],
    ['BRIG', 'Brigada / Enfermaria', 'SERVICO', 1250, 850],
  ],
  // a, b, via, escada, ruido, lotacao
  trechos: [
    ['J11', 'AWS', 'Rua Norte', 'N', 2, 3], ['AWS', 'AZURE', 'Rua Norte', 'N', 2, 3], ['AZURE', 'J21', 'Rua Norte', 'N', 2, 2],
    ['J21', 'J31', 'Rua Norte (fundo da Arena)', 'N', 3, 2], ['J31', 'J41', 'Rua Norte (fundo do palco)', 'N', 4, 2],
    ['J41', 'SL', 'Degraus da Saída Leste', 'S', 2, 1],
    ['ENT', 'J12', 'Boulevard NEXT', 'N', 3, 4], ['J12', 'GCP', 'Boulevard NEXT', 'N', 3, 4],
    ['GCP', 'IBM', 'Boulevard NEXT', 'N', 3, 4], ['IBM', 'J22', 'Boulevard NEXT', 'N', 3, 4],
    ['J22', 'ARENA', 'Boulevard NEXT', 'N', 3, 5], ['ARENA', 'J32', 'Boulevard NEXT', 'N', 4, 5],
    ['J32', 'PALCO', 'Boulevard NEXT (frente do palco)', 'N', 5, 5], ['PALCO', 'ORACLE', 'Boulevard NEXT (frente do palco)', 'N', 5, 4],
    ['ORACLE', 'J42', 'Boulevard NEXT', 'N', 4, 3], ['J42', 'R1', 'Passagem da Rampa', 'N', 2, 1],
    ['SO', 'J13', 'Rua Sul', 'N', 1, 1], ['J13', 'J23', 'Rua Sul', 'N', 1, 1],
    ['J23', 'NVIDIA', 'Rua Sul', 'N', 1, 2], ['NVIDIA', 'LABS', 'Rua Sul', 'N', 1, 2], ['LABS', 'J33', 'Rua Sul', 'N', 1, 2],
    ['J33', 'CI', 'Rua Sul', 'N', 1, 2], ['CI', 'ACOLH', 'Rua Sul', 'N', 1, 1],
    ['ORACLE', 'CI', 'Corredor Interno', 'N', 2, 5],
    ['ACOLH', 'J43', 'Rua Sul', 'N', 1, 1], ['J43', 'BRIG', 'Passagem da Rampa', 'N', 1, 1], ['BRIG', 'R2', 'Passagem da Rampa', 'N', 1, 1],
    ['J11', 'J12', 'Av. Oeste', 'N', 2, 2], ['J12', 'CRED', 'Av. Oeste', 'N', 3, 4], ['CRED', 'ALIM', 'Av. Oeste', 'N', 3, 4],
    ['ALIM', 'STARTUPS', 'Av. Oeste', 'N', 2, 3], ['STARTUPS', 'J13', 'Av. Oeste', 'N', 2, 2],
    ['SN', 'J21', 'Av. A', 'N', 1, 1], ['J21', 'J22', 'Av. A (lateral da Arena)', 'N', 3, 3], ['J22', 'J23', 'Av. A', 'N', 2, 2],
    ['J31', 'J32', 'Av. B (lateral do palco)', 'N', 5, 3], ['J32', 'WC', 'Av. B', 'N', 3, 4],
    ['WC', 'J33', 'Av. B', 'N', 2, 3], ['J33', 'SS', 'Av. B', 'N', 1, 2],
    ['J41', 'J42', 'Av. Leste (lateral do palco)', 'N', 4, 2],
    ['J42', 'J43', 'Degraus de serviço (Av. Leste)', 'S', 1, 1],
    ['R1', 'R2', 'Rampa Leste', 'N', 1, 1],
  ],
  // programação ILUSTRATIVA: ponto, título, início, fim, ruído previsto
  programacao: [
    ['CRED', 'Credenciamento e retirada de pulseiras', '08:30', '18:00', 2],
    ['ACOLH', 'Sala de Acolhimento aberta (espaço silencioso)', '09:00', '18:00', 1],
    ['PALCO', 'Keynote de abertura', '10:00', '11:00', 5],
    ['PALCO', 'Painel: IA que amplia pessoas', '11:30', '12:30', 4],
    ['ALIM', 'Almoço (horário de pico)', '12:00', '14:00', 3],
    ['ARENA', 'Final do hackathon Tech4Change', '13:00', '17:00', 4],
    ['ORACLE', 'Demo: AI Vector Search na prática', '14:00', '14:40', 3],
    ['LABS', 'Workshop de robótica', '15:00', '16:00', 3],
    ['STARTUPS', 'Pitch das startups', '15:30', '16:30', 3],
    ['PALCO', 'Show de encerramento', '17:30', '18:30', 5],
  ],
  testes: [['ORACLE', 'ACOLH'], ['ORACLE', 'SAIDA'], ['AWS', 'ACOLH'], ['ENT', 'ARENA']],
}, import.meta.url);
