-- Rodar como ADMIN (uma vez)
GRANT DB_DEVELOPER_ROLE   TO acesso_app;
GRANT CREATE MINING MODEL TO acesso_app;
GRANT EXECUTE ON DBMS_VECTOR TO acesso_app;
GRANT EXECUTE ON DBMS_CLOUD  TO acesso_app;
ALTER USER acesso_app QUOTA UNLIMITED ON DATA;
