-- GERADO por db/seed/expo.mjs — não edite à mão. Cenário ILUSTRATIVO / dados sintéticos.
SET DEFINE OFF
DECLARE v_ev NUMBER; BEGIN
  SELECT MAX(id) INTO v_ev FROM ac_evento WHERE codigo = 'EXPO26';
  IF v_ev IS NOT NULL THEN
    DELETE FROM ac_reporte WHERE evento_id = v_ev;
    DELETE FROM ac_trecho  WHERE evento_id = v_ev;
    DELETE FROM ac_ponto   WHERE evento_id = v_ev;
    DELETE FROM ac_area    WHERE evento_id = v_ev;
    DELETE FROM ac_evento  WHERE id = v_ev;
  END IF;
  COMMIT;
END;
/
MERGE INTO ac_perfil t USING (SELECT 'PADRAO' codigo, 'Sem restrição' nome, 'N' evita_escada, 1 peso_ruido, 1 peso_lotacao, 1.3 velocidade_ms, 'Caminho mais curto, evitando só o que está muito cheio.' descricao FROM dual
  UNION ALL SELECT 'CADEIRANTE' codigo, 'Cadeirante / carrinho de bebê' nome, 'S' evita_escada, 1 peso_ruido, 4 peso_lotacao, 1 velocidade_ms, 'Sem escadas nem degraus; foge de multidão, onde a cadeira não passa.' descricao FROM dual
  UNION ALL SELECT 'MOBILIDADE' codigo, 'Muletas / mobilidade reduzida' nome, 'S' evita_escada, 1 peso_ruido, 3 peso_lotacao, 0.7 velocidade_ms, 'Sem escadas; prefere trechos com menos gente.' descricao FROM dual
  UNION ALL SELECT 'NEURODIVERGENTE' codigo, 'Neurodivergente / sensível a estímulos' nome, 'N' evita_escada, 6 peso_ruido, 5 peso_lotacao, 1.2 velocidade_ms, 'Prioriza silêncio e pouca gente, mesmo que o caminho seja mais longo.' descricao FROM dual) s
ON (t.codigo = s.codigo)
WHEN MATCHED THEN UPDATE SET t.nome=s.nome, t.evita_escada=s.evita_escada, t.peso_ruido=s.peso_ruido, t.peso_lotacao=s.peso_lotacao, t.velocidade_ms=s.velocidade_ms, t.descricao=s.descricao
WHEN NOT MATCHED THEN INSERT (codigo,nome,evita_escada,peso_ruido,peso_lotacao,velocidade_ms,descricao) VALUES (s.codigo,s.nome,s.evita_escada,s.peso_ruido,s.peso_lotacao,s.velocidade_ms,s.descricao);
INSERT INTO ac_evento (codigo, nome, local, largura_px, altura_px, escala_m_px, descricao, origem_padrao) VALUES ('EXPO26', 'Expo Inclusão 2026', 'Pavilhão Expo', 1400, 1000, 0.2, 'Cenário genérico de demonstração — planta sintética.', 'ENT');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_STAND_A','Estandes A','STAND',180,180,290,290,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_ALIM','Praça de Alimentação','ALIMENTACAO',530,180,290,290,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_PALCO','Palco Principal','PALCO',880,180,290,290,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_TEC','Área Técnica','TECNICA',1230,180,110,290,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_STAND_B','Estandes B','STAND',180,530,290,290,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_STAND_C','Estandes C','STAND',530,530,290,290,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_EST42','Estande 42 — TechBrasil','STAND',880,530,290,100,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_CORR','Corredor Interno','CORREDOR',1045,630,30,220,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_WC','Banheiro Adaptado','BANHEIRO_ADAP',880,670,150,150,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_ACOLH','Sala de Acolhimento','ACOLHIMENTO',1085,670,85,150,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'A_RAMPA','Rampa Leste','RAMPA',1275,530,50,290,NULL,NULL);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'ENT','Entrada / Saída Principal','SAIDA',50,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'SN','Saída de Emergência Norte','SAIDA',500,50);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'SL','Saída de Emergência Leste (degraus)','SAIDA',1350,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'SS','Saída de Emergência Sul','SAIDA',850,950);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'SO','Saída de Emergência Oeste','SAIDA',50,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J11','Rua Norte × Av. Oeste','CRUZAMENTO',150,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J21','Rua Norte × Av. A','CRUZAMENTO',500,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J31','Rua Norte × Av. B','CRUZAMENTO',850,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J41','Rua Norte × Av. Leste','CRUZAMENTO',1200,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J12','Rua Central × Av. Oeste','CRUZAMENTO',150,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J22','Rua Central × Av. A','CRUZAMENTO',500,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J32','Rua Central × Av. B','CRUZAMENTO',850,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J42','Rua Central × Av. Leste','CRUZAMENTO',1200,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J13','Rua Sul × Av. Oeste','CRUZAMENTO',150,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J23','Rua Sul × Av. A','CRUZAMENTO',500,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J33','Rua Sul × Av. B','CRUZAMENTO',850,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'J43','Rua Sul × Av. Leste','CRUZAMENTO',1200,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'R1','Rampa Leste (topo)','RAMPA',1300,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'R2','Rampa Leste (base)','RAMPA',1300,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'STAND','Stand Nosso Produto','STAND',325,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'AUD','Auditório B','STAND',325,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'ALIM','Praça de Alimentação','ALIMENTACAO',675,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'PALCO','Palco Principal','PALCO',960,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'EST42','Estande 42 — TechBrasil','STAND',1060,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'CI','Corredor Interno × Rua Sul','CRUZAMENTO',1060,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'WC','Banheiro Adaptado','BANHEIRO_ADAP',850,700);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),'ACOLH','Sala de Acolhimento','ACOLHIMENTO',1130,850);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J11'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='AUD'),'Rua Norte',35,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='AUD'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J21'),'Rua Norte',35,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J21'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J31'),'Rua Norte',70,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J31'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J41'),'Rua Norte (fundo do palco)',70,'N','S',4,2,4,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J41'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='SL'),'Degraus da Saída Leste',30,'S','N',2,1,2,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='ENT'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J12'),'Rua Central',20,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J12'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='STAND'),'Rua Central',35,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='STAND'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J22'),'Rua Central',35,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J22'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='ALIM'),'Rua Central',35,'N','S',3,5,3,5);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='ALIM'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J32'),'Rua Central',35,'N','S',4,5,4,5);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J32'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='PALCO'),'Rua Central (frente do palco)',22,'N','S',5,5,5,5);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='PALCO'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='EST42'),'Rua Central (frente do palco)',20,'N','S',5,4,5,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='EST42'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J42'),'Rua Central',28,'N','S',4,3,4,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J42'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='R1'),'Passagem da Rampa',20,'N','S',2,1,2,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='SO'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J13'),'Rua Sul',20,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J13'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J23'),'Rua Sul',70,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J23'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J33'),'Rua Sul',70,'N','S',1,2,1,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J33'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='CI'),'Rua Sul',42,'N','S',1,2,1,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='CI'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='ACOLH'),'Rua Sul',14,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='EST42'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='CI'),'Corredor Interno',70,'N','S',2,5,2,5);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='ACOLH'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J43'),'Rua Sul',14,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J43'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='R2'),'Passagem da Rampa',20,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J11'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J12'),'Av. Oeste',70,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J12'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J13'),'Av. Oeste',70,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='SN'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J21'),'Av. A',20,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J21'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J22'),'Av. A',70,'N','S',3,3,3,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J22'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J23'),'Av. A',70,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J31'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J32'),'Av. B (lateral do palco)',70,'N','S',5,3,5,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J32'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='WC'),'Av. B',40,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='WC'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J33'),'Av. B',30,'N','S',2,3,2,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J33'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='SS'),'Av. B',20,'N','S',1,2,1,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J41'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J42'),'Av. Leste (lateral do palco)',70,'N','S',4,2,4,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J42'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='J43'),'Degraus de serviço (Av. Leste)',70,'S','N',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='EXPO26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='R1'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='EXPO26') AND codigo='R2'),'Rampa Leste',70,'N','S',1,1,1,1);
COMMIT;
