-- GERADO por db/seed/next.mjs — não edite à mão. Cenário ILUSTRATIVO / dados sintéticos.
SET DEFINE OFF
DECLARE v_ev NUMBER; BEGIN
  SELECT MAX(id) INTO v_ev FROM ac_evento WHERE codigo = 'NEXT26';
  IF v_ev IS NOT NULL THEN
    DELETE FROM ac_reporte WHERE evento_id = v_ev;
    DELETE FROM ac_trecho  WHERE evento_id = v_ev;
    DELETE FROM ac_ponto   WHERE evento_id = v_ev;
    DELETE FROM ac_area    WHERE evento_id = v_ev;
    DELETE FROM ac_evento  WHERE id = v_ev;
  END IF;
  COMMIT;
END;
/
MERGE INTO ac_perfil t USING (SELECT 'PADRAO' codigo, 'Sem restrição' nome, 'N' evita_escada, 1 peso_ruido, 1 peso_lotacao, 1.3 velocidade_ms, 'Caminho mais curto, evitando só o que está muito cheio.' descricao FROM dual
  UNION ALL SELECT 'CADEIRANTE' codigo, 'Cadeirante / carrinho de bebê' nome, 'S' evita_escada, 1 peso_ruido, 4 peso_lotacao, 1 velocidade_ms, 'Sem escadas nem degraus; foge de multidão, onde a cadeira não passa.' descricao FROM dual
  UNION ALL SELECT 'MOBILIDADE' codigo, 'Muletas / mobilidade reduzida' nome, 'S' evita_escada, 1 peso_ruido, 3 peso_lotacao, 0.7 velocidade_ms, 'Sem escadas; prefere trechos com menos gente.' descricao FROM dual
  UNION ALL SELECT 'NEURODIVERGENTE' codigo, 'Neurodivergente / sensível a estímulos' nome, 'N' evita_escada, 6 peso_ruido, 5 peso_lotacao, 1.2 velocidade_ms, 'Prioriza silêncio e pouca gente, mesmo que o caminho seja mais longo.' descricao FROM dual) s
ON (t.codigo = s.codigo)
WHEN MATCHED THEN UPDATE SET t.nome=s.nome, t.evita_escada=s.evita_escada, t.peso_ruido=s.peso_ruido, t.peso_lotacao=s.peso_lotacao, t.velocidade_ms=s.velocidade_ms, t.descricao=s.descricao
WHEN NOT MATCHED THEN INSERT (codigo,nome,evita_escada,peso_ruido,peso_lotacao,velocidade_ms,descricao) VALUES (s.codigo,s.nome,s.evita_escada,s.peso_ruido,s.peso_lotacao,s.velocidade_ms,s.descricao);
INSERT INTO ac_evento (codigo, nome, local, largura_px, altura_px, escala_m_px, descricao, origem_padrao) VALUES ('NEXT26', 'FIAP NEXT 2026', 'Pavilhão principal', 1400, 1000, 0.2, 'Planta ilustrativa para demonstração — layout fictício.', 'ENT');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_AWS','AWS','STAND',180,180,140,130,'#ff9900','Cloud Street');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_AZURE','Microsoft Azure','STAND',330,180,140,130,'#2f8fe8','Cloud Street');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_GCP','Google Cloud','STAND',180,340,140,130,'#34a853','Cloud Street');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_IBM','IBM','STAND',330,340,140,130,'#6f8cff','Cloud Street');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_ARENA','Arena Tech4Change','ARENA',530,180,290,290,'#a855f7','Final do hackathon');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_PALCO','Palco Principal','PALCO',880,180,290,290,'#ef4444','Keynotes');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_TEC','Streaming','TECNICA',1230,180,110,290,'#475569','Área técnica');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_ALIM','Praça de Alimentação','ALIMENTACAO',180,530,290,140,'#f59e0b',NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_STARTUPS','Startups FIAP','STAND',180,690,290,130,'#22d3ee','Vila de startups');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_NVIDIA','NVIDIA','STAND',530,530,140,290,'#76b900','IA & GPUs');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_LABS','FIAP Labs','STAND',680,530,140,290,'#ed145b','Robótica & IA');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_ORACLE','Oracle Cloud','STAND',880,530,290,100,'#c74634','OCI · Autonomous AI Database');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_CORR','Corredor Interno','CORREDOR',1045,630,30,220,NULL,NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_WC','Banheiro Adaptado','BANHEIRO_ADAP',880,670,150,150,'#38bdf8',NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_ACOLH','Sala de Acolhimento','ACOLHIMENTO',1085,670,85,150,'#2dd4bf','Espaço sensorial');
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_RAMPA','Rampa Leste','RAMPA',1275,530,50,290,'#84cc16',NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_CRED','Credenciamento','SERVICO',20,560,110,70,'#64748b',NULL);
INSERT INTO ac_area (evento_id,codigo,nome,tipo,x,y,largura,altura,cor,subtitulo) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'A_BRIG','Brigada / Enfermaria','SERVICO',1180,880,140,60,'#f43f5e',NULL);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'ENT','Entrada / Saída Principal','SAIDA',50,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'SN','Saída de Emergência Norte','SAIDA',500,50);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'SL','Saída de Emergência Leste (degraus)','SAIDA',1350,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'SS','Saída de Emergência Sul','SAIDA',850,950);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'SO','Saída de Emergência Oeste','SAIDA',50,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J11','Rua Norte × Av. Oeste','CRUZAMENTO',150,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J21','Rua Norte × Av. A','CRUZAMENTO',500,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J31','Rua Norte × Av. B','CRUZAMENTO',850,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J41','Rua Norte × Av. Leste','CRUZAMENTO',1200,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J12','Boulevard × Av. Oeste','CRUZAMENTO',150,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J22','Boulevard × Av. A','CRUZAMENTO',500,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J32','Boulevard × Av. B','CRUZAMENTO',850,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J42','Boulevard × Av. Leste','CRUZAMENTO',1200,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J13','Rua Sul × Av. Oeste','CRUZAMENTO',150,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J23','Rua Sul × Av. A','CRUZAMENTO',500,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J33','Rua Sul × Av. B','CRUZAMENTO',850,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'J43','Rua Sul × Av. Leste','CRUZAMENTO',1200,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'R1','Rampa Leste (topo)','RAMPA',1300,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'R2','Rampa Leste (base)','RAMPA',1300,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'CI','Corredor Interno × Rua Sul','CRUZAMENTO',1060,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'AWS','Stand AWS','STAND',250,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'AZURE','Stand Microsoft Azure','STAND',400,150);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'GCP','Stand Google Cloud','STAND',250,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'IBM','Stand IBM','STAND',400,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'ARENA','Arena Tech4Change','ARENA',675,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'PALCO','Palco Principal','PALCO',960,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'ORACLE','Stand Oracle Cloud','STAND',1060,500);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'ALIM','Praça de Alimentação','ALIMENTACAO',150,600);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'STARTUPS','Startups FIAP','STAND',150,755);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'NVIDIA','Stand NVIDIA','STAND',600,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'LABS','FIAP Labs','STAND',750,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'WC','Banheiro Adaptado','BANHEIRO_ADAP',850,700);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'ACOLH','Sala de Acolhimento','ACOLHIMENTO',1130,850);
INSERT INTO ac_ponto (evento_id,codigo,nome,tipo,x,y) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),'BRIG','Brigada / Enfermaria','SERVICO',1250,850);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J11'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='AWS'),'Rua Norte',20,'N','S',2,3,2,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='AWS'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='AZURE'),'Rua Norte',30,'N','S',2,3,2,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='AZURE'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J21'),'Rua Norte',20,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J21'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J31'),'Rua Norte (fundo da Arena)',70,'N','S',3,2,3,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J31'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J41'),'Rua Norte (fundo do palco)',70,'N','S',4,2,4,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J41'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='SL'),'Degraus da Saída Leste',30,'S','N',2,1,2,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ENT'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J12'),'Boulevard NEXT',20,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J12'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='GCP'),'Boulevard NEXT',20,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='GCP'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='IBM'),'Boulevard NEXT',30,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='IBM'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J22'),'Boulevard NEXT',20,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J22'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ARENA'),'Boulevard NEXT',35,'N','S',3,5,3,5);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ARENA'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J32'),'Boulevard NEXT',35,'N','S',4,5,4,5);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J32'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='PALCO'),'Boulevard NEXT (frente do palco)',22,'N','S',5,5,5,5);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='PALCO'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ORACLE'),'Boulevard NEXT (frente do palco)',20,'N','S',5,4,5,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ORACLE'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J42'),'Boulevard NEXT',28,'N','S',4,3,4,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J42'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='R1'),'Passagem da Rampa',20,'N','S',2,1,2,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='SO'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J13'),'Rua Sul',20,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J13'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J23'),'Rua Sul',70,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J23'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='NVIDIA'),'Rua Sul',20,'N','S',1,2,1,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='NVIDIA'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='LABS'),'Rua Sul',30,'N','S',1,2,1,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='LABS'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J33'),'Rua Sul',20,'N','S',1,2,1,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J33'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='CI'),'Rua Sul',42,'N','S',1,2,1,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='CI'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ACOLH'),'Rua Sul',14,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ORACLE'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='CI'),'Corredor Interno',70,'N','S',2,5,2,5);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ACOLH'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J43'),'Rua Sul',14,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J43'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='BRIG'),'Passagem da Rampa',10,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='BRIG'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='R2'),'Passagem da Rampa',10,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J11'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J12'),'Av. Oeste',70,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J12'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ALIM'),'Av. Oeste',20,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='ALIM'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='STARTUPS'),'Av. Oeste',31,'N','S',2,3,2,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='STARTUPS'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J13'),'Av. Oeste',19,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='SN'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J21'),'Av. A',20,'N','S',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J21'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J22'),'Av. A (lateral da Arena)',70,'N','S',3,3,3,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J22'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J23'),'Av. A',70,'N','S',2,2,2,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J31'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J32'),'Av. B (lateral do palco)',70,'N','S',5,3,5,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J32'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='WC'),'Av. B',40,'N','S',3,4,3,4);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='WC'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J33'),'Av. B',30,'N','S',2,3,2,3);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J33'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='SS'),'Av. B',20,'N','S',1,2,1,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J41'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J42'),'Av. Leste (lateral do palco)',70,'N','S',4,2,4,2);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J42'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='J43'),'Degraus de serviço (Av. Leste)',70,'S','N',1,1,1,1);
INSERT INTO ac_trecho (evento_id,ponto_a,ponto_b,via,distancia,tem_escada,acessivel,ruido,lotacao,ruido_base,lotacao_base) VALUES ((SELECT id FROM ac_evento WHERE codigo='NEXT26'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='R1'),(SELECT id FROM ac_ponto WHERE evento_id=(SELECT id FROM ac_evento WHERE codigo='NEXT26') AND codigo='R2'),'Rampa Leste',70,'N','S',1,1,1,1);
COMMIT;
